import './globals.css'
import { Roboto_Condensed } from 'next/font/google'
import Navbar from '../components/Navbar/Navbar'
import Footer from '@/components/Footer/Footer'
import Image from 'next/image'
import logo from '../../public/assets/logo/logo.svg'
import Link from 'next/link'

const roboto = Roboto_Condensed({ subsets: ['latin'],  weight: ["300", "400", "700"] })

export const metadata = {
  title: 'Fuego',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body className={roboto.className}>
      <Link href=''><Image priority className='logo' alt='Fuego étterem logója' src={logo}/></Link> 
        <Navbar nav={true} />
          {children}
        <Navbar NavFooter={true}  />
        <Footer />
        </body>
    </html>
  )
}
