import './globals.css'
import { Roboto_Condensed } from 'next/font/google'
import Navbar from '../components/Navbar/Navbar'
import Footer from '@/components/Footer/Footer'
import Logo from '@/components/UI/Logo/Logo'


const roboto = Roboto_Condensed({ subsets: ['latin'],  weight: ["300", "400", "700"] })

export const metadata = {
  title: 'Fuego',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={roboto.className}>
        <Logo />
        <Navbar nav={true} />
          {children}
        <Navbar NavFooter={true}  />
        <Footer />
        </body>
    </html>
  )
}
