import './globals.css'
import { Inter, Dosis, Roboto_Condensed, Bebas_Neue } from 'next/font/google'
import Navbar from '../components/Navbar/Navbar'

const roboto = Roboto_Condensed({ subsets: ['latin'],  weight: ["300", "400", "700"] })

export const metadata = {
  title: 'Fuego',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Navbar />
        {children}
        </body>
    </html>
  )
}
